"""order_book_v2

Revision ID: 61247afbc73e
Revises: 18f37a37de31
Create Date: 2026-05-07 12:30:42.574448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61247afbc73e'
down_revision: Union[str, Sequence[str], None] = '18f37a37de31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=3), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'resolution', 'open_time', name='uq_candles_stock_res_open_time')
    )
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_index(op.f('ix_candles_open_time'), 'candles', ['open_time'], unique=False)
    op.create_index(op.f('ix_candles_stock_id'), 'candles', ['stock_id'], unique=False)
    op.create_index('ix_candles_stock_res_open_time_desc', 'candles', ['stock_id', 'resolution', 'open_time'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=6), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index('ix_orders_match', 'orders', ['stock_id', 'side', 'price', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_stock_id'), 'orders', ['stock_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('executed_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('buy_order_id', sa.BigInteger(), nullable=True),
    sa.Column('sell_order_id', sa.BigInteger(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('aggressor_side', sa.String(length=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buy_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sell_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executed_trades_buyer_id'), 'executed_trades', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_executed_trades_id'), 'executed_trades', ['id'], unique=False)
    op.create_index(op.f('ix_executed_trades_seller_id'), 'executed_trades', ['seller_id'], unique=False)
    op.create_index(op.f('ix_executed_trades_stock_id'), 'executed_trades', ['stock_id'], unique=False)
    op.create_index('ix_executed_trades_stock_ts', 'executed_trades', ['stock_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_executed_trades_timestamp'), 'executed_trades', ['timestamp'], unique=False)
    # Add non-null columns with server defaults to avoid failing on existing rows.
    op.add_column('portfolio', sa.Column('avg_entry_price', sa.Float(), server_default='0', nullable=False))
    op.add_column('portfolio', sa.Column('margin_held', sa.Float(), server_default='0', nullable=False))
    op.add_column('stocks', sa.Column('last_traded_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('bid_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('ask_price', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('margin_held', sa.Float(), server_default='0', nullable=False))

    # Backfill last_traded_price for existing stocks (keep old .price as source of truth initially).
    op.execute("UPDATE stocks SET last_traded_price = price WHERE last_traded_price IS NULL")

    # Drop server defaults after backfill so application owns the values.
    op.alter_column('portfolio', 'avg_entry_price', server_default=None)
    op.alter_column('portfolio', 'margin_held', server_default=None)
    op.alter_column('users', 'margin_held', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'margin_held')
    op.drop_column('stocks', 'ask_price')
    op.drop_column('stocks', 'bid_price')
    op.drop_column('stocks', 'last_traded_price')
    op.drop_column('portfolio', 'margin_held')
    op.drop_column('portfolio', 'avg_entry_price')
    op.drop_index(op.f('ix_executed_trades_timestamp'), table_name='executed_trades')
    op.drop_index('ix_executed_trades_stock_ts', table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_stock_id'), table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_seller_id'), table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_id'), table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_buyer_id'), table_name='executed_trades')
    op.drop_table('executed_trades')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stock_id'), table_name='orders')
    op.drop_index('ix_orders_match', table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_candles_stock_res_open_time_desc', table_name='candles')
    op.drop_index(op.f('ix_candles_stock_id'), table_name='candles')
    op.drop_index(op.f('ix_candles_open_time'), table_name='candles')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
